# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"3\n\x08LogEntry\x12\n\n\x02op\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\r\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\r\"5\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x10\n\x08vote_for\x18\x02 \x01(\x08\"r\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x11\n\tleader_id\x18\x02 \x01(\r\x12\x16\n\x03log\x18\x03 \x03(\x0b\x32\t.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\r\x12\x0b\n\x03tag\x18\x05 \x01(\r\"F\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x12\n\nack_status\x18\x02 \x01(\x08\x12\x0b\n\x03tag\x18\x03 \x01(\r\"\x1b\n\rClientRequest\x12\n\n\x02op\x18\x01 \x01(\t2\xbd\x01\n\x08RaftNode\x12:\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\"\x00\x12@\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\"\x00\x12\x33\n\x14\x46orwardClientRequest\x12\x0e.ClientRequest\x1a\t.LogEntry\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=65
  _globals['_REQUESTVOTEREQUEST']._serialized_start=67
  _globals['_REQUESTVOTEREQUEST']._serialized_end=123
  _globals['_REQUESTVOTERESPONSE']._serialized_start=125
  _globals['_REQUESTVOTERESPONSE']._serialized_end=178
  _globals['_APPENDENTRIESREQUEST']._serialized_start=180
  _globals['_APPENDENTRIESREQUEST']._serialized_end=294
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=296
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=366
  _globals['_CLIENTREQUEST']._serialized_start=368
  _globals['_CLIENTREQUEST']._serialized_end=395
  _globals['_RAFTNODE']._serialized_start=398
  _globals['_RAFTNODE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
