// microservices/proto/pet_network.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pet_network.proto

package petnetwork

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportType int32

const (
	ReportType_LOST  ReportType = 0
	ReportType_FOUND ReportType = 1
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "LOST",
		1: "FOUND",
	}
	ReportType_value = map[string]int32{
		"LOST":  0,
		"FOUND": 1,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_pet_network_proto_enumTypes[0].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_pet_network_proto_enumTypes[0]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{0}
}

type ResolutionStrategy int32

const (
	ResolutionStrategy_LAST_WRITE_WINS ResolutionStrategy = 0
	ResolutionStrategy_HIGHEST_VERSION ResolutionStrategy = 1
	ResolutionStrategy_MANUAL_MERGE    ResolutionStrategy = 2
)

// Enum value maps for ResolutionStrategy.
var (
	ResolutionStrategy_name = map[int32]string{
		0: "LAST_WRITE_WINS",
		1: "HIGHEST_VERSION",
		2: "MANUAL_MERGE",
	}
	ResolutionStrategy_value = map[string]int32{
		"LAST_WRITE_WINS": 0,
		"HIGHEST_VERSION": 1,
		"MANUAL_MERGE":    2,
	}
)

func (x ResolutionStrategy) Enum() *ResolutionStrategy {
	p := new(ResolutionStrategy)
	*p = x
	return p
}

func (x ResolutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_pet_network_proto_enumTypes[1].Descriptor()
}

func (ResolutionStrategy) Type() protoreflect.EnumType {
	return &file_pet_network_proto_enumTypes[1]
}

func (x ResolutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionStrategy.Descriptor instead.
func (ResolutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{1}
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ReportType             `protobuf:"varint,2,opt,name=type,proto3,enum=petnetwork.ReportType" json:"type,omitempty"`
	PetType       string                 `protobuf:"bytes,3,opt,name=pet_type,json=petType,proto3" json:"pet_type,omitempty"`
	Breed         string                 `protobuf:"bytes,4,opt,name=breed,proto3" json:"breed,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Location      *Location              `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,9,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,10,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Region        string                 `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Version       int64                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_pet_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_LOST
}

func (x *Report) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *Report) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Report) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Report) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Report) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Report) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Report) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *Report) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *Report) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Report) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pet_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ReportType             `protobuf:"varint,1,opt,name=type,proto3,enum=petnetwork.ReportType" json:"type,omitempty"`
	PetType       string                 `protobuf:"bytes,2,opt,name=pet_type,json=petType,proto3" json:"pet_type,omitempty"`
	Breed         string                 `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Location      *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrls     []string               `protobuf:"bytes,7,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,8,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_pet_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReportRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_LOST
}

func (x *CreateReportRequest) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *CreateReportRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreateReportRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateReportRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CreateReportRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReportRequest) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *CreateReportRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_pet_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *CreateReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_pet_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ReportType             `protobuf:"varint,1,opt,name=type,proto3,enum=petnetwork.ReportType" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_pet_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{5}
}

func (x *ListReportsRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_LOST
}

func (x *ListReportsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReportsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_pet_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{6}
}

func (x *ListReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FindMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	MaxDistanceKm float64                `protobuf:"fixed64,2,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchesRequest) Reset() {
	*x = FindMatchesRequest{}
	mi := &file_pet_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchesRequest) ProtoMessage() {}

func (x *FindMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchesRequest.ProtoReflect.Descriptor instead.
func (*FindMatchesRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{7}
}

func (x *FindMatchesRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *FindMatchesRequest) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *FindMatchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchResult         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMatchesResponse) Reset() {
	*x = FindMatchesResponse{}
	mi := &file_pet_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMatchesResponse) ProtoMessage() {}

func (x *FindMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMatchesResponse.ProtoReflect.Descriptor instead.
func (*FindMatchesResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{8}
}

func (x *FindMatchesResponse) GetMatches() []*MatchResult {
	if x != nil {
		return x.Matches
	}
	return nil
}

type MatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	MatchScore    float64                `protobuf:"fixed64,2,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,3,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_pet_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{9}
}

func (x *MatchResult) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *MatchResult) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *MatchResult) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type MatchScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report1       *Report                `protobuf:"bytes,1,opt,name=report1,proto3" json:"report1,omitempty"`
	Report2       *Report                `protobuf:"bytes,2,opt,name=report2,proto3" json:"report2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchScoreRequest) Reset() {
	*x = MatchScoreRequest{}
	mi := &file_pet_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchScoreRequest) ProtoMessage() {}

func (x *MatchScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchScoreRequest.ProtoReflect.Descriptor instead.
func (*MatchScoreRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{10}
}

func (x *MatchScoreRequest) GetReport1() *Report {
	if x != nil {
		return x.Report1
	}
	return nil
}

func (x *MatchScoreRequest) GetReport2() *Report {
	if x != nil {
		return x.Report2
	}
	return nil
}

type MatchScoreResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Score            float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	MatchingFeatures []string               `protobuf:"bytes,2,rep,name=matching_features,json=matchingFeatures,proto3" json:"matching_features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchScoreResponse) Reset() {
	*x = MatchScoreResponse{}
	mi := &file_pet_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchScoreResponse) ProtoMessage() {}

func (x *MatchScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchScoreResponse.ProtoReflect.Descriptor instead.
func (*MatchScoreResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{11}
}

func (x *MatchScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MatchScoreResponse) GetMatchingFeatures() []string {
	if x != nil {
		return x.MatchingFeatures
	}
	return nil
}

type NearbySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Location              `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Type          ReportType             `protobuf:"varint,3,opt,name=type,proto3,enum=petnetwork.ReportType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbySearchRequest) Reset() {
	*x = NearbySearchRequest{}
	mi := &file_pet_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbySearchRequest) ProtoMessage() {}

func (x *NearbySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbySearchRequest.ProtoReflect.Descriptor instead.
func (*NearbySearchRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{12}
}

func (x *NearbySearchRequest) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *NearbySearchRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *NearbySearchRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_LOST
}

type NearbySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbySearchResponse) Reset() {
	*x = NearbySearchResponse{}
	mi := &file_pet_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbySearchResponse) ProtoMessage() {}

func (x *NearbySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbySearchResponse.ProtoReflect.Descriptor instead.
func (*NearbySearchResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{13}
}

func (x *NearbySearchResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

type IndexLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexLocationRequest) Reset() {
	*x = IndexLocationRequest{}
	mi := &file_pet_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexLocationRequest) ProtoMessage() {}

func (x *IndexLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexLocationRequest.ProtoReflect.Descriptor instead.
func (*IndexLocationRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{14}
}

func (x *IndexLocationRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *IndexLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type IndexLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexLocationResponse) Reset() {
	*x = IndexLocationResponse{}
	mi := &file_pet_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexLocationResponse) ProtoMessage() {}

func (x *IndexLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexLocationResponse.ProtoReflect.Descriptor instead.
func (*IndexLocationResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{15}
}

func (x *IndexLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Center        *Location              `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	PetTypes      []string               `protobuf:"bytes,4,rep,name=pet_types,json=petTypes,proto3" json:"pet_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pet_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRequest) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *SubscribeRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *SubscribeRequest) GetPetTypes() []string {
	if x != nil {
		return x.PetTypes
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Report        *Report                `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_pet_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{17}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *Alert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_pet_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{18}
}

func (x *UnsubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnsubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_pet_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{19}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAlertRequest) Reset() {
	*x = PublishAlertRequest{}
	mi := &file_pet_network_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAlertRequest) ProtoMessage() {}

func (x *PublishAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAlertRequest.ProtoReflect.Descriptor instead.
func (*PublishAlertRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{20}
}

func (x *PublishAlertRequest) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type PublishAlertResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SubscribersNotified int32                  `protobuf:"varint,1,opt,name=subscribers_notified,json=subscribersNotified,proto3" json:"subscribers_notified,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PublishAlertResponse) Reset() {
	*x = PublishAlertResponse{}
	mi := &file_pet_network_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAlertResponse) ProtoMessage() {}

func (x *PublishAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAlertResponse.ProtoReflect.Descriptor instead.
func (*PublishAlertResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{21}
}

func (x *PublishAlertResponse) GetSubscribersNotified() int32 {
	if x != nil {
		return x.SubscribersNotified
	}
	return 0
}

type SyncDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRegion  string                 `protobuf:"bytes,1,opt,name=source_region,json=sourceRegion,proto3" json:"source_region,omitempty"`
	Reports       []*Report              `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataRequest) Reset() {
	*x = SyncDataRequest{}
	mi := &file_pet_network_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataRequest) ProtoMessage() {}

func (x *SyncDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataRequest.ProtoReflect.Descriptor instead.
func (*SyncDataRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{22}
}

func (x *SyncDataRequest) GetSourceRegion() string {
	if x != nil {
		return x.SourceRegion
	}
	return ""
}

func (x *SyncDataRequest) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *SyncDataRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SyncDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SyncedIds     []string               `protobuf:"bytes,2,rep,name=synced_ids,json=syncedIds,proto3" json:"synced_ids,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataResponse) Reset() {
	*x = SyncDataResponse{}
	mi := &file_pet_network_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataResponse) ProtoMessage() {}

func (x *SyncDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataResponse.ProtoReflect.Descriptor instead.
func (*SyncDataResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{23}
}

func (x *SyncDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncDataResponse) GetSyncedIds() []string {
	if x != nil {
		return x.SyncedIds
	}
	return nil
}

func (x *SyncDataResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	LocalVersion  *Report                `protobuf:"bytes,2,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	RemoteVersion *Report                `protobuf:"bytes,3,opt,name=remote_version,json=remoteVersion,proto3" json:"remote_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_pet_network_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{24}
}

func (x *Conflict) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *Conflict) GetLocalVersion() *Report {
	if x != nil {
		return x.LocalVersion
	}
	return nil
}

func (x *Conflict) GetRemoteVersion() *Report {
	if x != nil {
		return x.RemoteVersion
	}
	return nil
}

type ConflictResolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conflict      *Conflict              `protobuf:"bytes,1,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Strategy      ResolutionStrategy     `protobuf:"varint,2,opt,name=strategy,proto3,enum=petnetwork.ResolutionStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictResolutionRequest) Reset() {
	*x = ConflictResolutionRequest{}
	mi := &file_pet_network_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictResolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictResolutionRequest) ProtoMessage() {}

func (x *ConflictResolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictResolutionRequest.ProtoReflect.Descriptor instead.
func (*ConflictResolutionRequest) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{25}
}

func (x *ConflictResolutionRequest) GetConflict() *Conflict {
	if x != nil {
		return x.Conflict
	}
	return nil
}

func (x *ConflictResolutionRequest) GetStrategy() ResolutionStrategy {
	if x != nil {
		return x.Strategy
	}
	return ResolutionStrategy_LAST_WRITE_WINS
}

type ConflictResolutionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResolvedReport *Report                `protobuf:"bytes,1,opt,name=resolved_report,json=resolvedReport,proto3" json:"resolved_report,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConflictResolutionResponse) Reset() {
	*x = ConflictResolutionResponse{}
	mi := &file_pet_network_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictResolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictResolutionResponse) ProtoMessage() {}

func (x *ConflictResolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_network_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictResolutionResponse.ProtoReflect.Descriptor instead.
func (*ConflictResolutionResponse) Descriptor() ([]byte, []int) {
	return file_pet_network_proto_rawDescGZIP(), []int{26}
}

func (x *ConflictResolutionResponse) GetResolvedReport() *Report {
	if x != nil {
		return x.ResolvedReport
	}
	return nil
}

func (x *ConflictResolutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pet_network_proto protoreflect.FileDescriptor

const file_pet_network_proto_rawDesc = "" +
	"\n" +
	"\x11pet_network.proto\x12\n" +
	"petnetwork\"\xf1\x02\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.petnetwork.ReportTypeR\x04type\x12\x19\n" +
	"\bpet_type\x18\x03 \x01(\tR\apetType\x12\x14\n" +
	"\x05breed\x18\x04 \x01(\tR\x05breed\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x120\n" +
	"\blocation\x18\x06 \x01(\v2\x14.petnetwork.LocationR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\t \x03(\tR\tphotoUrls\x12!\n" +
	"\fcontact_info\x18\n" +
	" \x01(\tR\vcontactInfo\x12\x16\n" +
	"\x06region\x18\v \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversion\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x9e\x02\n" +
	"\x13CreateReportRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.petnetwork.ReportTypeR\x04type\x12\x19\n" +
	"\bpet_type\x18\x02 \x01(\tR\apetType\x12\x14\n" +
	"\x05breed\x18\x03 \x01(\tR\x05breed\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x120\n" +
	"\blocation\x18\x05 \x01(\v2\x14.petnetwork.LocationR\blocation\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\a \x03(\tR\tphotoUrls\x12!\n" +
	"\fcontact_info\x18\b \x01(\tR\vcontactInfo\"v\n" +
	"\x14CreateReportResponse\x12*\n" +
	"\x06report\x18\x01 \x01(\v2\x12.petnetwork.ReportR\x06report\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\"\n" +
	"\x10GetReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x12ListReportsRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.petnetwork.ReportTypeR\x04type\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Y\n" +
	"\x13ListReportsResponse\x12,\n" +
	"\areports\x18\x01 \x03(\v2\x12.petnetwork.ReportR\areports\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"o\n" +
	"\x12FindMatchesRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12&\n" +
	"\x0fmax_distance_km\x18\x02 \x01(\x01R\rmaxDistanceKm\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"H\n" +
	"\x13FindMatchesResponse\x121\n" +
	"\amatches\x18\x01 \x03(\v2\x17.petnetwork.MatchResultR\amatches\"{\n" +
	"\vMatchResult\x12*\n" +
	"\x06report\x18\x01 \x01(\v2\x12.petnetwork.ReportR\x06report\x12\x1f\n" +
	"\vmatch_score\x18\x02 \x01(\x01R\n" +
	"matchScore\x12\x1f\n" +
	"\vdistance_km\x18\x03 \x01(\x01R\n" +
	"distanceKm\"o\n" +
	"\x11MatchScoreRequest\x12,\n" +
	"\areport1\x18\x01 \x01(\v2\x12.petnetwork.ReportR\areport1\x12,\n" +
	"\areport2\x18\x02 \x01(\v2\x12.petnetwork.ReportR\areport2\"W\n" +
	"\x12MatchScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12+\n" +
	"\x11matching_features\x18\x02 \x03(\tR\x10matchingFeatures\"\x8c\x01\n" +
	"\x13NearbySearchRequest\x12,\n" +
	"\x06center\x18\x01 \x01(\v2\x14.petnetwork.LocationR\x06center\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.petnetwork.ReportTypeR\x04type\"D\n" +
	"\x14NearbySearchResponse\x12,\n" +
	"\areports\x18\x01 \x03(\v2\x12.petnetwork.ReportR\areports\"e\n" +
	"\x14IndexLocationRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x120\n" +
	"\blocation\x18\x02 \x01(\v2\x14.petnetwork.LocationR\blocation\"1\n" +
	"\x15IndexLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x01\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x06center\x18\x02 \x01(\v2\x14.petnetwork.LocationR\x06center\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x1b\n" +
	"\tpet_types\x18\x04 \x03(\tR\bpetTypes\"\x84\x01\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12*\n" +
	"\x06report\x18\x02 \x01(\v2\x12.petnetwork.ReportR\x06report\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"V\n" +
	"\x12UnsubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x13PublishAlertRequest\x12*\n" +
	"\x06report\x18\x01 \x01(\v2\x12.petnetwork.ReportR\x06report\"I\n" +
	"\x14PublishAlertResponse\x121\n" +
	"\x14subscribers_notified\x18\x01 \x01(\x05R\x13subscribersNotified\"\x82\x01\n" +
	"\x0fSyncDataRequest\x12#\n" +
	"\rsource_region\x18\x01 \x01(\tR\fsourceRegion\x12,\n" +
	"\areports\x18\x02 \x03(\v2\x12.petnetwork.ReportR\areports\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x7f\n" +
	"\x10SyncDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"synced_ids\x18\x02 \x03(\tR\tsyncedIds\x122\n" +
	"\tconflicts\x18\x03 \x03(\v2\x14.petnetwork.ConflictR\tconflicts\"\x9b\x01\n" +
	"\bConflict\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x127\n" +
	"\rlocal_version\x18\x02 \x01(\v2\x12.petnetwork.ReportR\flocalVersion\x129\n" +
	"\x0eremote_version\x18\x03 \x01(\v2\x12.petnetwork.ReportR\rremoteVersion\"\x89\x01\n" +
	"\x19ConflictResolutionRequest\x120\n" +
	"\bconflict\x18\x01 \x01(\v2\x14.petnetwork.ConflictR\bconflict\x12:\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x1e.petnetwork.ResolutionStrategyR\bstrategy\"s\n" +
	"\x1aConflictResolutionResponse\x12;\n" +
	"\x0fresolved_report\x18\x01 \x01(\v2\x12.petnetwork.ReportR\x0eresolvedReport\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess*!\n" +
	"\n" +
	"ReportType\x12\b\n" +
	"\x04LOST\x10\x00\x12\t\n" +
	"\x05FOUND\x10\x01*P\n" +
	"\x12ResolutionStrategy\x12\x13\n" +
	"\x0fLAST_WRITE_WINS\x10\x00\x12\x13\n" +
	"\x0fHIGHEST_VERSION\x10\x01\x12\x10\n" +
	"\fMANUAL_MERGE\x10\x022\xf1\x01\n" +
	"\rReportService\x12Q\n" +
	"\fCreateReport\x12\x1f.petnetwork.CreateReportRequest\x1a .petnetwork.CreateReportResponse\x12=\n" +
	"\tGetReport\x12\x1c.petnetwork.GetReportRequest\x1a\x12.petnetwork.Report\x12N\n" +
	"\vListReports\x12\x1e.petnetwork.ListReportsRequest\x1a\x1f.petnetwork.ListReportsResponse2\xb7\x01\n" +
	"\x0fMatchingService\x12N\n" +
	"\vFindMatches\x12\x1e.petnetwork.FindMatchesRequest\x1a\x1f.petnetwork.FindMatchesResponse\x12T\n" +
	"\x13CalculateMatchScore\x12\x1d.petnetwork.MatchScoreRequest\x1a\x1e.petnetwork.MatchScoreResponse2\xb5\x01\n" +
	"\n" +
	"GeoService\x12Q\n" +
	"\fNearbySearch\x12\x1f.petnetwork.NearbySearchRequest\x1a .petnetwork.NearbySearchResponse\x12T\n" +
	"\rIndexLocation\x12 .petnetwork.IndexLocationRequest\x1a!.petnetwork.IndexLocationResponse2\xf1\x01\n" +
	"\fAlertService\x12>\n" +
	"\tSubscribe\x12\x1c.petnetwork.SubscribeRequest\x1a\x11.petnetwork.Alert0\x01\x12N\n" +
	"\vUnsubscribe\x12\x1e.petnetwork.UnsubscribeRequest\x1a\x1f.petnetwork.UnsubscribeResponse\x12Q\n" +
	"\fPublishAlert\x12\x1f.petnetwork.PublishAlertRequest\x1a .petnetwork.PublishAlertResponse2\xc1\x01\n" +
	"\x12ReplicationService\x12I\n" +
	"\bSyncData\x12\x1b.petnetwork.SyncDataRequest\x1a\x1c.petnetwork.SyncDataResponse(\x010\x01\x12`\n" +
	"\x0fResolveConflict\x12%.petnetwork.ConflictResolutionRequest\x1a&.petnetwork.ConflictResolutionResponseB\x0fZ\r./;petnetworkb\x06proto3"

var (
	file_pet_network_proto_rawDescOnce sync.Once
	file_pet_network_proto_rawDescData []byte
)

func file_pet_network_proto_rawDescGZIP() []byte {
	file_pet_network_proto_rawDescOnce.Do(func() {
		file_pet_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_network_proto_rawDesc), len(file_pet_network_proto_rawDesc)))
	})
	return file_pet_network_proto_rawDescData
}

var file_pet_network_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pet_network_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pet_network_proto_goTypes = []any{
	(ReportType)(0),                    // 0: petnetwork.ReportType
	(ResolutionStrategy)(0),            // 1: petnetwork.ResolutionStrategy
	(*Report)(nil),                     // 2: petnetwork.Report
	(*Location)(nil),                   // 3: petnetwork.Location
	(*CreateReportRequest)(nil),        // 4: petnetwork.CreateReportRequest
	(*CreateReportResponse)(nil),       // 5: petnetwork.CreateReportResponse
	(*GetReportRequest)(nil),           // 6: petnetwork.GetReportRequest
	(*ListReportsRequest)(nil),         // 7: petnetwork.ListReportsRequest
	(*ListReportsResponse)(nil),        // 8: petnetwork.ListReportsResponse
	(*FindMatchesRequest)(nil),         // 9: petnetwork.FindMatchesRequest
	(*FindMatchesResponse)(nil),        // 10: petnetwork.FindMatchesResponse
	(*MatchResult)(nil),                // 11: petnetwork.MatchResult
	(*MatchScoreRequest)(nil),          // 12: petnetwork.MatchScoreRequest
	(*MatchScoreResponse)(nil),         // 13: petnetwork.MatchScoreResponse
	(*NearbySearchRequest)(nil),        // 14: petnetwork.NearbySearchRequest
	(*NearbySearchResponse)(nil),       // 15: petnetwork.NearbySearchResponse
	(*IndexLocationRequest)(nil),       // 16: petnetwork.IndexLocationRequest
	(*IndexLocationResponse)(nil),      // 17: petnetwork.IndexLocationResponse
	(*SubscribeRequest)(nil),           // 18: petnetwork.SubscribeRequest
	(*Alert)(nil),                      // 19: petnetwork.Alert
	(*UnsubscribeRequest)(nil),         // 20: petnetwork.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),        // 21: petnetwork.UnsubscribeResponse
	(*PublishAlertRequest)(nil),        // 22: petnetwork.PublishAlertRequest
	(*PublishAlertResponse)(nil),       // 23: petnetwork.PublishAlertResponse
	(*SyncDataRequest)(nil),            // 24: petnetwork.SyncDataRequest
	(*SyncDataResponse)(nil),           // 25: petnetwork.SyncDataResponse
	(*Conflict)(nil),                   // 26: petnetwork.Conflict
	(*ConflictResolutionRequest)(nil),  // 27: petnetwork.ConflictResolutionRequest
	(*ConflictResolutionResponse)(nil), // 28: petnetwork.ConflictResolutionResponse
}
var file_pet_network_proto_depIdxs = []int32{
	0,  // 0: petnetwork.Report.type:type_name -> petnetwork.ReportType
	3,  // 1: petnetwork.Report.location:type_name -> petnetwork.Location
	0,  // 2: petnetwork.CreateReportRequest.type:type_name -> petnetwork.ReportType
	3,  // 3: petnetwork.CreateReportRequest.location:type_name -> petnetwork.Location
	2,  // 4: petnetwork.CreateReportResponse.report:type_name -> petnetwork.Report
	0,  // 5: petnetwork.ListReportsRequest.type:type_name -> petnetwork.ReportType
	2,  // 6: petnetwork.ListReportsResponse.reports:type_name -> petnetwork.Report
	11, // 7: petnetwork.FindMatchesResponse.matches:type_name -> petnetwork.MatchResult
	2,  // 8: petnetwork.MatchResult.report:type_name -> petnetwork.Report
	2,  // 9: petnetwork.MatchScoreRequest.report1:type_name -> petnetwork.Report
	2,  // 10: petnetwork.MatchScoreRequest.report2:type_name -> petnetwork.Report
	3,  // 11: petnetwork.NearbySearchRequest.center:type_name -> petnetwork.Location
	0,  // 12: petnetwork.NearbySearchRequest.type:type_name -> petnetwork.ReportType
	2,  // 13: petnetwork.NearbySearchResponse.reports:type_name -> petnetwork.Report
	3,  // 14: petnetwork.IndexLocationRequest.location:type_name -> petnetwork.Location
	3,  // 15: petnetwork.SubscribeRequest.center:type_name -> petnetwork.Location
	2,  // 16: petnetwork.Alert.report:type_name -> petnetwork.Report
	2,  // 17: petnetwork.PublishAlertRequest.report:type_name -> petnetwork.Report
	2,  // 18: petnetwork.SyncDataRequest.reports:type_name -> petnetwork.Report
	26, // 19: petnetwork.SyncDataResponse.conflicts:type_name -> petnetwork.Conflict
	2,  // 20: petnetwork.Conflict.local_version:type_name -> petnetwork.Report
	2,  // 21: petnetwork.Conflict.remote_version:type_name -> petnetwork.Report
	26, // 22: petnetwork.ConflictResolutionRequest.conflict:type_name -> petnetwork.Conflict
	1,  // 23: petnetwork.ConflictResolutionRequest.strategy:type_name -> petnetwork.ResolutionStrategy
	2,  // 24: petnetwork.ConflictResolutionResponse.resolved_report:type_name -> petnetwork.Report
	4,  // 25: petnetwork.ReportService.CreateReport:input_type -> petnetwork.CreateReportRequest
	6,  // 26: petnetwork.ReportService.GetReport:input_type -> petnetwork.GetReportRequest
	7,  // 27: petnetwork.ReportService.ListReports:input_type -> petnetwork.ListReportsRequest
	9,  // 28: petnetwork.MatchingService.FindMatches:input_type -> petnetwork.FindMatchesRequest
	12, // 29: petnetwork.MatchingService.CalculateMatchScore:input_type -> petnetwork.MatchScoreRequest
	14, // 30: petnetwork.GeoService.NearbySearch:input_type -> petnetwork.NearbySearchRequest
	16, // 31: petnetwork.GeoService.IndexLocation:input_type -> petnetwork.IndexLocationRequest
	18, // 32: petnetwork.AlertService.Subscribe:input_type -> petnetwork.SubscribeRequest
	20, // 33: petnetwork.AlertService.Unsubscribe:input_type -> petnetwork.UnsubscribeRequest
	22, // 34: petnetwork.AlertService.PublishAlert:input_type -> petnetwork.PublishAlertRequest
	24, // 35: petnetwork.ReplicationService.SyncData:input_type -> petnetwork.SyncDataRequest
	27, // 36: petnetwork.ReplicationService.ResolveConflict:input_type -> petnetwork.ConflictResolutionRequest
	5,  // 37: petnetwork.ReportService.CreateReport:output_type -> petnetwork.CreateReportResponse
	2,  // 38: petnetwork.ReportService.GetReport:output_type -> petnetwork.Report
	8,  // 39: petnetwork.ReportService.ListReports:output_type -> petnetwork.ListReportsResponse
	10, // 40: petnetwork.MatchingService.FindMatches:output_type -> petnetwork.FindMatchesResponse
	13, // 41: petnetwork.MatchingService.CalculateMatchScore:output_type -> petnetwork.MatchScoreResponse
	15, // 42: petnetwork.GeoService.NearbySearch:output_type -> petnetwork.NearbySearchResponse
	17, // 43: petnetwork.GeoService.IndexLocation:output_type -> petnetwork.IndexLocationResponse
	19, // 44: petnetwork.AlertService.Subscribe:output_type -> petnetwork.Alert
	21, // 45: petnetwork.AlertService.Unsubscribe:output_type -> petnetwork.UnsubscribeResponse
	23, // 46: petnetwork.AlertService.PublishAlert:output_type -> petnetwork.PublishAlertResponse
	25, // 47: petnetwork.ReplicationService.SyncData:output_type -> petnetwork.SyncDataResponse
	28, // 48: petnetwork.ReplicationService.ResolveConflict:output_type -> petnetwork.ConflictResolutionResponse
	37, // [37:49] is the sub-list for method output_type
	25, // [25:37] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_pet_network_proto_init() }
func file_pet_network_proto_init() {
	if File_pet_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_network_proto_rawDesc), len(file_pet_network_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_pet_network_proto_goTypes,
		DependencyIndexes: file_pet_network_proto_depIdxs,
		EnumInfos:         file_pet_network_proto_enumTypes,
		MessageInfos:      file_pet_network_proto_msgTypes,
	}.Build()
	File_pet_network_proto = out.File
	file_pet_network_proto_goTypes = nil
	file_pet_network_proto_depIdxs = nil
}
