# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_access.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_access.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_access.proto\x12\ndataaccess\"O\n\x11ReportTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\"\n\x06report\x18\x02 \x01(\x0b\x32\x12.dataaccess.Report\"\xfb\x01\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08pet_type\x18\x03 \x01(\t\x12\r\n\x05\x62reed\x18\x04 \x01(\t\x12\r\n\x05\x63olor\x18\x05 \x01(\t\x12\x10\n\x08latitude\x18\x06 \x01(\x01\x12\x11\n\tlongitude\x18\x07 \x01(\x01\x12\x0f\n\x07\x61\x64\x64ress\x18\x08 \x01(\t\x12\x11\n\ttimestamp\x18\t \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x12\n\nphoto_urls\x18\x0b \x03(\t\x12\x14\n\x0c\x63ontact_info\x18\x0c \x01(\t\x12\x0e\n\x06region\x18\r \x01(\t\x12\x0f\n\x07version\x18\x0e \x01(\x03\"Z\n\x0cVoteResponse\x12+\n\x04vote\x18\x01 \x01(\x0e\x32\x1d.dataaccess.VoteResponse.Vote\"\x1d\n\x04Vote\x12\n\n\x06\x43OMMIT\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01\"\'\n\rTransactionId\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc6\x01\n\x05TwoPC\x12\x46\n\x0bVoteRequest\x12\x1d.dataaccess.ReportTransaction\x1a\x18.dataaccess.VoteResponse\x12:\n\x0cGlobalCommit\x12\x19.dataaccess.TransactionId\x1a\x0f.dataaccess.Ack\x12\x39\n\x0bGlobalAbort\x12\x19.dataaccess.TransactionId\x1a\x0f.dataaccess.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTTRANSACTION']._serialized_start=33
  _globals['_REPORTTRANSACTION']._serialized_end=112
  _globals['_REPORT']._serialized_start=115
  _globals['_REPORT']._serialized_end=366
  _globals['_VOTERESPONSE']._serialized_start=368
  _globals['_VOTERESPONSE']._serialized_end=458
  _globals['_VOTERESPONSE_VOTE']._serialized_start=429
  _globals['_VOTERESPONSE_VOTE']._serialized_end=458
  _globals['_TRANSACTIONID']._serialized_start=460
  _globals['_TRANSACTIONID']._serialized_end=499
  _globals['_ACK']._serialized_start=501
  _globals['_ACK']._serialized_end=523
  _globals['_TWOPC']._serialized_start=526
  _globals['_TWOPC']._serialized_end=724
# @@protoc_insertion_point(module_scope)
