# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_access_pb2 as data__access__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_access_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoteRequest = channel.unary_unary(
                '/dataaccess.TwoPC/VoteRequest',
                request_serializer=data__access__pb2.ReportTransaction.SerializeToString,
                response_deserializer=data__access__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GlobalCommit = channel.unary_unary(
                '/dataaccess.TwoPC/GlobalCommit',
                request_serializer=data__access__pb2.TransactionId.SerializeToString,
                response_deserializer=data__access__pb2.Ack.FromString,
                _registered_method=True)
        self.GlobalAbort = channel.unary_unary(
                '/dataaccess.TwoPC/GlobalAbort',
                request_serializer=data__access__pb2.TransactionId.SerializeToString,
                response_deserializer=data__access__pb2.Ack.FromString,
                _registered_method=True)


class TwoPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoteRequest(self, request, context):
        """Coordinator -> Participant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalCommit(self, request, context):
        """Coordinator -> Participant final decision
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=data__access__pb2.ReportTransaction.FromString,
                    response_serializer=data__access__pb2.VoteResponse.SerializeToString,
            ),
            'GlobalCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalCommit,
                    request_deserializer=data__access__pb2.TransactionId.FromString,
                    response_serializer=data__access__pb2.Ack.SerializeToString,
            ),
            'GlobalAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalAbort,
                    request_deserializer=data__access__pb2.TransactionId.FromString,
                    response_serializer=data__access__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataaccess.TwoPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataaccess.TwoPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.TwoPC/VoteRequest',
            data__access__pb2.ReportTransaction.SerializeToString,
            data__access__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.TwoPC/GlobalCommit',
            data__access__pb2.TransactionId.SerializeToString,
            data__access__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.TwoPC/GlobalAbort',
            data__access__pb2.TransactionId.SerializeToString,
            data__access__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
